// INTRODUCTION
// ECMA SCRIPTS
// CHROME V8 ENGINE 
// JAVASCRIPT RUNTIME 
// NODEJS 
// HELLO WORLD WITH JS
// MODULES
// BROWSER VS NODE
// MODULES- Local,Built-In,Third Party 
// LOCAL Modules
// MODULE EXPORT- module.export=function;
// MODULE SCOPE
// MODULE WRAPPER
// MODULE CACHING
// IMPORT/EXPORT PATTERNS
// ES MODULE/ECMA MODULES- two TYPES-( Common JS & ES Modules)
// IMPORT JASON AND WATCH MODE(NODEMON)
// BUILT IN MODULE
// PATH MODULE
// CALLBACK PATTERN
// EVENTS MODULE
// CHARACTERSETS AND ENCODING-(UTF-08)
// STREAMS AND BUFFER- (master and Workers,cluster)
// ASYNCHRONOUS JAVASCRIPT
// FILE SYSTEM MODULE
// PROMISES
// STREAMS
// PIPES
// HTTP MODULES
// CREATING A WEB SERVER
// JSON RESPONSE
// HTML RESPONSE
// HTML TEMPLATE
// HTTP ROUTING
// WEB FRAMEWORKS
// LIBUV
// THREAD POOL
// THREAD POOL SIZE
// EVENT LOOP
// TIMER QUEUE
// I/O POLLING
// CLOSE QUEUE
// PACKAGE JSON
//INSTALLING AND USING PACKAGES
// DEPENDENCIES
// GLOBAL PACKAGES- NODEMON
// SCRIPTS
// PUBLISHING A PACKAGE
// BUILDING A CLI TOOL
// CLI OPTIONS
// INTERACTIVE CLI TOOLS
// CLUSTER
// WORKER THREADS
// DEPLOYMENT
// WRAPPING UP WITH WHERE TO SHIFT NEXT 